### ISSUE TITLE
Send proper message when client fails to ping http server

### ISSUE THREAD

**Issue by IfgiU** [Skidamek/AutoModpack#134] opened 2023-06-24 23:26 UTC
### Bug description

Hi!
I'm currently testing out this mod, and stumbled upon some weird behaviour:
When joining for the first time, everything works fine, the modpack gets downloaded by the client.
However, if I delete the instance where the mods are installed and create a new one that only runs AutoModpack,
it won't download the modpack again, leading to errors.
Is the server caching which players have downloaded the modpack?
If so, maybe this is the cause of it? Tho I haven't found a file that could be a cache.

### Steps to reproduce

1. Have a server with AutoModpack and a modpack
2. Have a client only with AutoModpack
3. Join
4. Quit Minecraft
5. Create new instance only with AutoModpack
6. Join
7. Fail to join because mods aren't present

### Expected behavior

Not failing to join

### Actual behavior

Failed to join

### Relevant logs

The only logs worthy to be mentioned are these two lines from the server:
`[23:02:43] [Netty Epoll Server IO #2/INFO]: MyUsername has installed AutoModpack.
[23:02:46] [Netty Epoll Server IO #2/INFO]: MyUsername has installed whole modpack`
The last message is definetly wrong, I had not installed the modpack.

### Minecraft version & Mod Loader

1.19.3 fabric

### Operating system

Windows 11

### AutoModpack version

3.3.6

### Other information

Also, `/automodpack generate` does not seem to help.

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment] 2023-06-25 08:52
Are you sure, you are creating completely fresh instance? Server does not have any cache. Only way it could let you join with false positive that you have installed modpack is to client have same modpack-content.json in /automodpack/modpacks/<modpack>/ as server provides...
I can't reproduce this by creating new instances using prism launcher.

**Comment by IfgiU** [comment] 2023-06-25 16:45
So, I think I found the problem.
The /automodpack/modpacks folder was empty, so it wasn't the problem here.
I'm also using Prism Launcher on the newest version, so the instances were clean.
It turns out that when the `hostIp` in `automodpack-server.json` doesn't match the actual IP,
the check for the modpack seems to get skipped. What I think was happening is that I installed the mod,
it auto-set the value to the current IP, I tried stuff, the next day the IP was resetted so it no longer matched,
so the error occured.

To reproduce, try setting `HostIp` to a wrong IP-Address on a server with AutoModpack and a Modpack and join only with AutoModpack.

**Comment by Skidamek** [comment] 2023-06-25 17:17
Alright, that makes a lot of sense. Then it's not really a bug, however i will implement some more logic to instead of let join the player kick them and send a proper message. Thanks!

**Comment by IfgiU** [comment] 2023-06-27 18:56
But how exactly can I keep the `hostIP` up to date?

**Comment by Skidamek** [comment] 2023-06-27 18:59
What do you mean up to date?
I does not, at first config generation it just gets your server's ip from this api https://ip.seeip.org/json
I many cases thanks to that you just don't even need to worry about setting proper ip there.
Then it doesn't change it, to let you configure that as you want to.

**Comment by IfgiU** [comment] 2023-06-29 15:44
Hi! Yeah, that would be really nice! I just don't want to login into the server and change the hostIp everytime the IP changes, so this option would be really cool!

**Comment by Skidamek** [comment] 2023-07-20 19:46
I implemented it, it will be in final 3.4.0, if you would like to try it pre-released then go ahead! :) [build-artifacts.zip](https://github.com/Skidamek/AutoModpack/suites/14452695765/artifacts/816005535)

**Comment by Skidamek** [comment] 2023-07-23 09:08
Implemented in 3.4.0

**Closed by Skidamek** 2023-07-23 09:08 UTC
Labels: enhancement
