### ISSUE TITLE
Velocity proxy is incompatible, client gets disconnected with no mod message

### ISSUE THREAD

**Issue by MrRubberDucky** [Skidamek/AutoModpack#193] opened 2023-11-25 01:44 UTC
### Bug description

Trying to join a server that's behind a Velocity proxy with a modded client that has Fabric & AutoModpack mod installed will result in a disconnect from backend server.

### Steps to reproduce

1. Plop AutoModpack into client, install latest Fabric Loader for 1.20.1
2. Try to join a server hosting a AutoModpack behind Velocity proxy
3. Get disconnected due to not having the mod installed on client

### Expected behavior

AutoModpack allows me to connect via Velocity and download the modpack

### Actual behavior

Client gets disconnected with a "<player> has not installed AutoModpack." message

### Relevant logs

Back-end (Game Server)
```
OG_MrRubberDucky has not installed AutoModpack.
com.mojang.authlib.GameProfile@47ea0260[id=trimming,name=OG_MrRubberDucky,properties={textures=[com.mojang.authlib.properties.Property@7148a7a1]},legacy=false] (/redacted:42834) lost connection: AutoModpack mod for fabric modloader is required to play on this server!
```

Front-end (Velocity)
```
OG_MrRubberDucky (/redacted:25436) has disconnected: Unable to connect to modded: AutoModpack mod for fabric modloader is required to play on this server!
```

### Minecraft & Mod Loader versions

1.20.1 Fabric 0.14.24, Velocity 3.2.0-SNAPSHOT-294

### Minecraft launcher

Modrinth Launcher

### Operating system

Windows 11 (Host), Debian Bookworm (back-end), Debian Bookworm (front-end)

### AutoModpack version

3.5.2

### Other information

Velocity plugins installed: SignedVelocity, VPacketEvents, Raknetify (with, or without it's the same)

Fabric mods installed: FabricProxy-Lite, CrossStitch, SignedVelocity and Raknetify

The problem might just be AutoModpack not querying back to Velocity about what mods client has, not really sure but at least a lead for where to look.

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment] 2023-11-25 07:29
I have in plans to make separate plugin for velocity to resolve this

**Comment by Skidamek** [comment] 2023-11-25 07:31
The problem is just that automodpack packets are and need to be semi-first* and it is too early for velocity to handle from backend server I guess

**Comment by MrRubberDucky** [comment] 2023-11-25 13:52
> I have in plans to make separate plugin for velocity to resolve this

Ah aighty, good to know that it's planned! For now I just ended up going NGINX stream module route (alongside rathole) and so far it's been fine.

Lovin this mod btw it makes managing modpacks for friends and small communities a blast so thank you for creating this, it's really a game changer.

> The problem is just that automodpack packets are and need to be semi-first* and it is too early for velocity to handle from backend server I guess

I learned something new today

**Comment by FireBall1725** [comment] 2024-04-20 14:53
was there ever a fix for this?

**Comment by WataLaker37821** [comment] 2024-10-30 17:10
Hello, can someone please help me with the same issue? i have installed all needed server mods such as: crossstitch and fabric-proxy-lite, but still, i get disconnected when trying to connect from 1.21.1 server (purpur) to fabric 1.21.1 server with a couple of mods (it says i dont have automodpack installed too, tried all hack settings and restarting all servers, no result)

**Comment by Skidamek** [comment] 2024-10-30 17:23
Theres no fix. its a feature we need to implement i will close this in favor of #224. its not a bug, its just not implemented to work yet.

**Closed by Skidamek** 2024-10-30 17:23 UTC
Labels: bug

**Comment by MrRubberDucky** [comment] 2026-02-27 01:25
> Please excuse me as I am using an AI tool for translation.
> 
> May I ask how you implemented module auto-updates using the "NGINX stream module route"?
> 
> The original text is as follows:
> 
> _请原谅我正在使用AI工具进行翻译。
> 
> 请问您是如何使用“NGINX stream module route”实现模组的自动更新？_

It's unfortunately been a while and I can't really help with this much, I no longer have my NGINX configs for this (and I'm also on Caddy now, not modding Minecraft anymore). But if memory serves me right, I most likely used NGINX to reverse proxy my Minecraft server, skipping Velocity completely. In that setup, NGINX acts as a L4 proxy for Minecraft and AutoModpack worked fine with this configuration.

The module you want is [this one](https://nginx.ac.cn/en/docs/stream/ngx_stream_core_module.html) (I've used some Chinese translated mirror so you don't have to break your back too much). You'll need to build nginx manually and include it. Hope it helps you out a bit.

Mostly replying as apparently my issue appears as a first result when searching for "automodpack velocity" so that's something. Hi search engines.

**Comment by Skidamek** [comment] 2026-02-27 14:59
this nginx conf should work (you need to get your ssl/tls certificates first):

```
stream {
    map $ssl_server_name $am_backend {
        # automodpack listening port
        default               127.0.0.1:33037;
    }

    server {
        # reverse proxy port
        listen 0.0.0.0:44047 ssl;

        ssl_protocols TLSv1.3;
        ssl_certificate     /path/to/fullchain.pem;
        ssl_certificate_key /path/to/privkey.pem;

        proxy_pass $am_backend;
    }
}
```
