### ISSUE TITLE
 AMP removes mod dependencies from client

### ISSUE THREAD

**Issue by mimi-min** [Skidamek/AutoModpack#195] opened 2023-12-07 08:04 UTC
### Bug description

AMP downloads the mods, but seems to skip their dependencies for some reason, even though they are on the server, and not set to ignore in config. **Edit: It seems they're getting completely removed by AMP as well.**

This is what I see when I load Minecraft (after disabling some mods that work when I install them manually, but crash the client when downloaded through AMP... I'll make a different report for that though, there are many issues to sort out)

![image](https://github.com/Skidamek/AutoModpack/assets/29613956/aa721f03-d4e1-4674-87c1-3d7f1aa3b459)

Also, after downloading and restarting, AMP and Forgified Fabric API are gone from my mod list, even though they are also present on the server.

### Steps to reproduce

1. Upload mods to server
2. Attempt to connect to server with client containing only AMP and Forgified Fabric API
3. Let AMP download mods
4. Restart MC client

### Expected behavior

For AMP to push the mod dependencies as well as the full mods, so the client can run.

### Actual behavior

Several dependencies have not been downloaded. **Edit: They also get removed after manually installing and restarting with AMP**

### Minecraft & Mod Loader versions

1.20.1, Forge 47.2.0, Forgified Fabric API 0.90.7

### Operating system

Windows 11, Debian 12 with OpenJDK 21 (friend had the same issue)

### AutoModpack version

3.5.2

### Other information

My friend and I have been struggling getting this mod to work, so I attempted to add you on Discord (@mimi_min) but I understand if it's uncomfortable or bothersome to offer one-on-one support. Unfortunately I will likely be adding many new bug reports... so I apologize in advance.

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by mimi-min** [comment] 2023-12-07 09:02
I just tried setting "autoExcludeServerSideMods" to false and there is still no change, mods are being downloaded without their dependencies, and AutoModpack is disappearing from the mod list (and mods folder), which prevents me from attempting to connect to the server. 

I did notice that while Forgified Fabric API also disappears from the modlist, "fabric-api-0.90.7+1.10.3+1.20.1.jar" appears in the mods folder.

I also noticed that the missing mods (aside from AMP) are appearing in the minecraft\Instances\(instance)\automodpack\modpacks\(world)\mods folder (client side), just not in the main mods folder, for whatever reason.

My next test was as follows: 

1. Manually install each of the dependencies
2. Re-install AMP
3. Start the client again

The result: I get this pop-up, and on my other monitor I can see all of the manually installed dependencies (and AMP) disappearing from my mod list, putting me back at square one.
![image](https://github.com/Skidamek/AutoModpack/assets/29613956/7e5517fa-d5c8-41a0-b82a-f6bd81d4514c)

**Comment by Debug-Dan** [comment] 2023-12-24 15:56
I would like to add that I'm also having this exact same issue. I can't even get the mod to function as intended (I'm using the forge version).

For me, it seems like mainly dependencies and also a client side mod was not copied over properly. I say this because the actual transfer part of the mod (transferring the mods from the server to the client) works perfectly fine, and I know this because there is a folder inside the automodpack folder where the mod stores all of the downloaded files. It seems like the problem is actually transferring all the files over to the mods folder, which it fails to do and therefore makes the client crash.

Additionally I would like to add that this mod crashed upon initial install, and I noticed in the server log it kept talking about certain Fabric APIs even though I'm using the forge version. The way I even got the mod to not crash the server was to download a mod named "Forgified Fabric API".

**Comment by Skidamek** [comment] 2024-03-09 18:36
Fixed in 4.0.0 beta 1!

**Comment by k2helix** [comment] 2024-06-26 11:43
This keeps happening in the latest version in Fabric. I'm using Minecraft 1.20.1. I think it happens if there are chained dependencies. For instance, the mod Better Animations Collection requires the mod Puzzles Lib, which then requires ForgeConfigApiPort which automodpack does not add to the mods folder but to the AMP one.

**Comment by Skidamek** [comment] 2024-06-26 14:15
Hopefully now it should work *almost* perfectly

**Closed** 2024-06-26 14:15 UTC
Labels: bug
