### ISSUE TITLE
ForgeConfigAPIPort and Pehkui compatibility error as an OP

### ISSUE THREAD

**Issue by Davithy** [Skidamek/AutoModpack#82] opened 2023-01-13 08:40 UTC
**Describe the bug**
Simply put, when the mods ForgeConfigAPIPort, Pehkui, and Automodpack are installed to a server, when an opped player joins, the error pictured below shows up. I've pin pointed these three mods specifically, but it's not an error between ForgeConfigAPIPort and Pehkui, as the crash only occurs when Automodpack and these 2 mods are present.

**To Reproduce**

1. With a server, add the 3 mods mentioned
2. Join the server, and give the player op
3. If done correctly it should instantly give the error

**Expected Behavior**
The 3 mods do not cause any such error.

**AutoModpack and Minecraft Version**

- Minecraft 1.19.2
- Fabric 0.14.12
- Automodpack-1.19-2.4.1
- ForgeConfigAPIPort-v4.2.10-1.19.2-Fabric
- Pehkui-3.6.3+1.14.4-1.19.3

![image](https://user-images.githubusercontent.com/105761502/212274544-04d912b8-7e77-4469-85e9-c43be0e50c31.png)

**Comment by Skidamek** [comment] 2023-01-13 09:24
Duplicate of #69

**Closed** 2023-01-13 09:24 UTC
Labels: bug, duplicate
