### ISSUE TITLE
Can't restart/stop server

### ISSUE THREAD

**Issue by rogi27** [Skidamek/AutoModpack#120] opened 2023-06-07 16:34 UTC
**Describe the bug**
Simply the server doesn't stop and hangs, neither by /stop command or control panel.

**To Reproduce**
1. Run server on Pterodactyl CP (possibly works with simple Docker container)
2. After server is fully loaded try to stop it

**Expected behavior**
Server should stop

**Screenshots**
![2023-06-07_19-17](https://github.com/Skidamek/AutoModpack/assets/10144091/333aed86-4c3b-41f7-b46b-82510a5c3ccb)

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - 3.3.0 and 3.3.1 with 1.19.4 Fabric/Quilt

**Client & Server log**
[Log](https://mclo.gs/2DgtzH2)

**Comment by Skidamek** [comment] 2023-06-07 16:38
Are you sure it is related to automodpack?

**Comment by rogi27** [comment] 2023-06-07 16:43
> Are you sure it is related to automodpack?

I tried to stop server using built-in command without any other mods except FAPI.
Even fully clearing config files didn't work.

**Comment by Skidamek** [comment] 2023-06-07 16:44
Server stops completely normally without automodpack?

**Comment by rogi27** [comment] 2023-06-07 16:45
> Server stops completely normally without automodpack?

Yes, but with it it just hangs up, maybe it's awaiting for host to close itself, but I tried doing /automodpack host stop before using /stop command and still got stuck.

**Comment by Skidamek** [comment] 2023-06-07 16:47
Interesting, this has never happened to me, I'll try to investigate it

**Comment by rogi27** [comment] 2023-06-07 16:49
> Interesting, this has never happened to me, I'll try to investigate it

Tested it locally, seems to be a pretty serious problem because even on Arch Linux with Java 17 and same setup server still hangs up. Would be nice to see a fix, otherwise you did a very nice mod 👍🏻

**Comment by Skidamek** [comment] 2023-06-08 12:11
Can you try new 3.3.1 release?

**Comment by Skidamek** [comment] 2023-06-08 12:45
That's so strange because on my fedora 37 linux server closes without issues...
Are you using docker container? If so could you try without?

**Comment by Eatham532** [comment] 2023-06-12 09:02
It looks like your server did stop. Because everything saved properly. Well everything stopped except the modpack hosting which is most likely the reason. 

If that is not the reason then I am guessing pterodactyl detects a stopped server when it reads a certain line in console. And that may not be shown when running with the mod.

**Comment by Skidamek** [comment] 2023-06-12 10:50
Thanks @Eatham532 you made me thinking, can you @rogi27 please try disabling automodpack host in config before starting the server and then try to stop whole server, to be sure that this is something related to my badly implemented http server?

**Comment by rogi27** [comment] 2023-06-12 10:51
> It looks like your server did stop. Because everything saved properly.
> 
> I am guessing pterodactyl detects a stopped server when it reads a certain line in console. And that may not be shown when running with the mod.
> 
> Does it work without the mod installed?

Again, I installed it locally, without ANY other mod, WITHOUT Docker, and still got same problem on clean install.

**Comment by Eatham532** [comment] 2023-06-12 10:53
Does it happen without the mod installed?

**Comment by Eatham532** [comment] 2023-06-12 10:55
@rogi27 Can you create a fresh server. Fabric. But don't add any mods. Check to see if you still have the issue.

**Comment by rogi27** [comment] 2023-06-12 10:56
> @rogi27 Can you create a fresh server. Fabric. But don't add any mods. Check to see if you still have the issue. 

What do you think fresh install means?

**Comment by Skidamek** [comment] 2023-06-12 11:10
> Thanks @Eatham532 you made me thinking, can you @rogi27 please try disabling automodpack host in config before starting the server and then try to stop whole server, to be sure that this is something related to my badly implemented http server?

Could you try?

**Comment by rogi27** [comment] 2023-06-12 11:11
> > Thanks @Eatham532 you made me thinking, can you @rogi27 please try disabling automodpack host in config before starting the server and then try to stop whole server, to be sure that this is something related to my badly implemented http server?
> 
> Could you try?

I will try.

**Comment by littlewing1977** [comment] 2023-06-14 22:46
I'm having the same issue.  I'm running this mod on Minecraft 1.20.1 in an AMP instance that is running on Ubuntu.  I can't shutdown or restart.  It just hangs.  The server is set to sleep when nobody is on it also.  It hangs when trying to sleep also.  So every time I want to log in, I have to force kill Minecraft server, then start it again.

**Comment by Skidamek** [comment] 2023-06-15 02:22
Interesting, could you try to disable modpack host in config and check if the same problem also accurees?

**Comment by littlewing1977** [comment] 2023-06-15 15:15
I did some testing this morning.

I removed AutoModpack.  The server shuts down as expected.
I then reinstalled AutoModpack.  With no changes to configuration, the server fails to complete the shutdown.
I ran the command /Automodpack host stop.  The server still fails to shut down.
I edited the server config file and set modpackHost to false.  The server fails to shut down.

I noticed the output to the console is exactly the same in every scenario.  See below.
After “All dimensions are saved,” the server still says it’s shutting down and I have to force kill it.  When the mod is NOT installed, it completes the shut down immediately after that line.

I think I covered everything.  Let me know if you want me to try anything else.  Can we confirm that the HTTP server has completely stopped?  Could that be holding it up?


Server thread/INFO

10:52:18

Stopping the server

Stopped modpack hosting

Stopping server

Saving players

Saving worlds

10:52:19

Saving chunks for level 'ServerLevel[world]'/minecraft:overworld

Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether

Saving chunks for level 'ServerLevel[world]'/minecraft:the_end

ThreadedAnvilChunkStorage (world): All chunks are saved

ThreadedAnvilChunkStorage (DIM-1): All chunks are saved

ThreadedAnvilChunkStorage (DIM1): All chunks are saved

ThreadedAnvilChunkStorage: All dimensions are saved


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by suerion** [comment] 2023-06-15 15:47
I think i had the same issue on Windows xD but don't get it as Bug. I closed allways the batch command, could be the same problem, and i think about it, because the bug was here on Linux docker. there it was more seen as a problem as on windows

**Comment by Skidamek** [comment] 2023-06-15 15:51
Nah, that's a really issue, get it reproduced on bash without any panels, dockers, etc... no clue what could cause this yet...

**Comment by MikolajMNK19** [comment] 2023-06-24 06:39
I've got the same issue on windows

**Comment by MikolajMNK19** [comment] 2023-06-24 07:41
Update: just moved my newly configured server to linux and the issue persists

**Comment by Skidamek** [comment] 2023-06-24 12:06
Fixed in 3.3.6

**Closed by Skidamek** 2023-06-24 12:06 UTC
Labels: bug
